# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jacob Barrett
tagline:          'Info'
description:      'Software Engineer<br>Game Developer<br>Musician'
url:              https://jcbarrett1.github.io
baseurl:          https://jcbarrett1.github.io/

author:
  name:           'Jacob Barrett'
  url:            https://twitter.com/mdo

gems:                [jekyll-paginate, jekyll-gist]
paginate:            5
paginate_path:       "page:num"
plugins: [jekyll-paginate, jekyll-gist]
# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde
